name: Maven deploy release
on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven settings
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          server-id: eredrim
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build the package
        run: mvn --batch-mode clean install -T4

      - name: Deploy the package
        run: mvn --batch-mode deploy -DaltDeploymentRepository="eredrim::default::https://repo.eredrim.fr/repository/maven-releases/"
        env:
          MAVEN_USERNAME: ${{ secrets.MVN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MVN_PASSWORD }}